@startuml hanging

class Game{

}

class Word{

}

class Player{

}

class Accused{

}

class Draw{

}

class Power{

}

Game "1" --* "1" Word
Game "1" --* "1" Draw
Game "1" --> "1" Player
Game "1" o-- "0..*" Power 
Player "1" <-- "0..*" Power
Game "1" <-- "0..*" Accused 

@enduml